version: "3.3"

services:
  db:
    container_name: bench_db
    image: mongo
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /data/db/logs
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    restart: always
